import = ["/home/Douglas/.config/alacritty/catpuccino-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.normal]
family = "SpaceMonoNerdFont"
style = "Regular"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "PageDown"

[window]
opacity = 0.75
